DEFAULT_PASSWORD_LENGTH = 16
MIN_PASSWORD_LENGTH = 8
MAX_PASSWORD_LENGTH = 1_000_000  # Limite maximale pour la génération

DEFAULT_USE_UPPERCASE = True
DEFAULT_USE_LOWERCASE = True
DEFAULT_USE_DIGITS = True
DEFAULT_USE_SYMBOLS = True
DEFAULT_EXCLUDE_AMBIGUOUS = False

AMBIGUOUS_CHARS = 'l1O0' 